name: Depo_mountain
version: '${version}'
main: deponn.depo_mountain.Depo_mountain
api-version: 1.16
authors: [ deponn ]
description: create mountain

commands: #自作プラグインのコマンドを宣言
  /mountain:
    description: ラピスラズリブロックの点の補間により山を作成します。
    usage: //mountain [-a:空気以外も書き換え] [-b:境界の高さを取得] [-n:補完の頂点数]
    permission: mountain

permissions:
  mountain:
    description: op only
    default: op