name: Depo_Mountain_1_16_5
version: '${version}'
main: depo_mountain.depo_mountain_1_16_5.Depo_Mountain_1_16_5
api-version: 1.16
authors: [ Deponn ]
description: create mountain


commands: #自作プラグインのコマンドを宣言
  /DpMountain:
    description: ラピスラズリブロックの点の補間により山を作成します。
    usage: //DpMountain [-NoBorder:境界を無視する] [-NoLimited:高さ範囲無視] [-degree:傾き] [-k:補完の頂点数] [-resource:資源量]
    permission: mountain
  /DpGround:
    description: 資源を含んだ地面生成。
    usage: //DpGround [-Box 地面のみ変換ではなく箱型にする] [-NoLimited:高さ範囲無視] [-resource:資源量]
    permission: mountain

permissions:
  mountain:
    description: op only
    default: op