name: Depo_Mountain_1_16_5
version: '${version}'
main: depo_mountain.depo_mountain_1_16_5.Depo_Mountain_1_16_5
api-version: 1.16
authors: [ Deponn ]
description: create mountain


commands: #自作プラグインのコマンドを宣言
  /DpMountain:
    description: ラピスラズリブロックの点の補間により山を作成します。
    usage: //DpMountain [-OnlyAir:空気以外も書き換え] [-NoBorder:境界の高さを取得] [-NoLimited:境界の高さを取得] [-degree:傾き] [-k:補完の頂点数]
    permission: mountain

permissions:
  mountain:
    description: op only
    default: op